### ISSUE TITLE
publish artifacts

### ISSUE THREAD

**Issue by michelleN** [deislabs/smi-adapter-istio#40]

**Comment by grampelberg** [comment]
We need this over in deislabs/smi-metrics as well. Right now it is on my personal dockerhub account which isn't sustainable.

**Comment by michelleN** [comment]
There is a deislabs dockerhub org that I have admin access to. We could create a repo to host `deislabs/smi-metrics` images and another one for deislabs/smi-adapter-istio` images. Any objections to that @lachie83 @grampelberg ?

**Comment by grampelberg** [comment]
Sounds fantastic to me!

**Comment by michelleN** [comment]
created both repos. Now working on building/publishing the image to that repo on every CI merge to master run
