### ISSUE TITLE
Status/Future of this Repo

### ISSUE THREAD

**Issue by keithmattix** [deislabs/smi-adapter-istio#96]
:wave: Hi all - I'd like to discuss the future of this repo. The last meaningful library (Go) commit was pre-2020, and the issues requesting istio version support are piling up. I've spent the last few days attempting to convert this project to Go modules (`dep ensure` hangs and is no longer supported), and the dependency situation is....messy to say the least; several package revisions no longer exist, and I still haven't found a working combination. Obviously, having an SMI adapter for Istio would be fantastic, but I'm curious as to the official status/support of this repository.

**Comment by bridgetkromhout** [comment]
Thanks, @keithmattix! I've added this as a discussion item for the June 9th community meeting - https://docs.google.com/document/d/1NTBaJf6LhUBlF8_lfvBBt_MbyPvT-6CZNg6Ckpm_yCo/edit?usp=sharing - please edit as desired.

**Comment by jamielennox** [comment]
Was there an outcome to this? I'm not sure how SMI is going in general but to a casual observer the istio support seems basically stopped.

**Comment by keithmattix** [comment]
Development of Istio support has shifted to https://github.com/nicholasjackson/istio-smi-controller for the time being 😄

**Comment by tillig** [comment]
Can we get the README in this repo updated to indicate that? It's not super obvious until you start trolling through the issues list.

**Comment by bridgetkromhout** [comment]
Closing due to project archival: https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/
